spring:
  profiles:
    active: dev

server:
  port: 9008


netty:
  deviceClientPort: 4070
  webClientPort: 4072
  webClientIp: 192.168.2.147


logging:
  level:
    root: INFO
#    io:
#      netty: DEBUG
