spring:
  application:
    name: door-gateway
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 600000
        max-pool-size: 20
        min-idle: 5
        connection-test-query: select 1
        pool-name: ibasicHikariCP
      # 配置默认数据源
      primary: base
      datasource:
        # 数据源-1，名称为 base
        base:
          username: root
          password: Fh123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.40.20.14:3306/FiberCard?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
  activemq:
    broker-url: tcp://10.40.20.16:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30

activemq:
  monitor:
    queue: fc_access_controller
    queue-gateway: fc_system

netty:
  port: 4070
  connections: 2048