spring:
  profiles:
    #激活开发环境
    active: dev

server:
  port: 9008

netty:
  tcp:
    # 服务端口
    port: 4070
    # 绑定的网卡
    ip: 0.0.0.0
    # 服务端连接队列长度
    connections: 2048

logging:
  level:
    root: INFO
#    io:
#      netty: DEBUG
